### ISSUE TITLE
Several unit-tests fails

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#148]
I have a bunch of unit-tests failing, all with the error message: `Assert.IsTrue failed. Expected Win32Exception error should be: [67], got: [21]`.
- AlphaFS_Copy
- CreateDirectory
- Delete
- Delete (why do we have two tests with the same name?
- EnumerateDirectories
- EnumerateFiles
- EnumerateFileSystemEntries
- FileSystem_Class_FileInfo
- GetDirectories
- GetFiles
- GetFileSystemEntries

One test, `Copy`, fails with the message: `Assert.IsTrue failed. [System.IO.FileNotFoundException] should have been caught.`

And finally there are two tests called `Move` (again, why two with the same name?), that fail with the error:  `Assert.IsTrue failed. Expected Win32Exception error should be: [5], got: [183]`

@Yomodo Any idea what's happened here?

**Comment by Yomodo** [comment]
The tests with the same name would be individually for File and Directory class.
AlphaFS_Copy is specific for Directory class as .NET does not have this method.

On my system (Win 8) and test system (Win 7) the File.Copy/Move would _sometimes_ fail with one of the above exceptions, but on a re-run they run fine.
As far as I can tell this seems to be related to disconnected network shares.

As for the other unit test: Enumerate/Get: these all call EnumerateFileSystemEntryInfosCore() so it would indicate that there's an issue there.

However, I just synced with the latest develop, did a rebuild, and all unit tests here run fine.

**Comment by alphaleonis** [comment]
Hmm... well, sounds like a test error of some sort. The 21/67 error indicates that it is expecting `ERROR_BAD_NET_NAME` but got `ERROR_NOT_READY` for some reason.

The tests seem to fail consistently, no matter how many times I run them. :/

**Comment by Yomodo** [comment]
There seems to be a difference in returned error code when the path is a UNC path.

Uhm, perhaps a reboot?

**Comment by Yomodo** [comment]
Just installed a fresh VM with Server 2012 R2, all tests: OK.

**Comment by alphaleonis** [comment]
Alright, something about the tests in my environment then. I'll investigate further when I get the chance.

**Comment by rstarkov** [comment]
I'm getting the same results as alphaleonis. It's a Win7 64-bit system. At least for the Move, it makes sense to receive 183, as it's a more specific error (ERROR_ALREADY_EXISTS, which is indeed true).

I notice that the source path is located in C:\Windows and that the test expects ERROR_ACCESS_DENIED. Could it be that these tests are tuned to run with UAC on? I'm running them as admin with UAC off.

**Comment by Yomodo** [comment]
Hi, yes, in some test require admin right and will report if this is not the case
(volume label for example)

**Comment by mikequinlan** [comment]
This is FYI in case it helps...

I am getting a failed tests in Move (AlphaFS.UnitTest.dll!AlphaFS.UnitTest.FileTest.Move() Line 2546). The message says that the LastError should be 5 but is 183.

In file File.CopyMove.cs beginning at line 1115. NativeMethods.MoveFIleWithProgress is called and it returns a non-zero value (error). Marshal.GetLastWin32Error() returns 183 ERROR_ALREADY_EXISTS. The code at line 1183 converts this to an exception with the Win32 error set to ERROR_ALREADY EXISTS (183). This is all correct.

The source file name is "\\?\C:\WINDOWS\autologon.log" and the destination file name is "\\?\C:\Users\myuser\AppData\Local\Temp\File-Move-sc432cwb.pue\autologon.log". The destination file name is a folder and it does exist.

The problem occurs at line 1342 in AlphaFS.UnitTest where the return value expected to be 5, which is wrong. The return value is 183 which is correct. A possible fix is to change line 1321 to set expectedLastError to ERROR_ALREADY_EXISTS instead of ERROR_ACCESS_DENIED.

The is on WIndows 10 Pro running on a Parallels VM on OS X El Capitan.

**Comment by alphaleonis** [comment]
Currently unable to reproduce this problem, so closing this for now.
