### ISSUE TITLE
Provide a way to retrieve errors when you choose to ContinueOnException

### ISSUE THREAD

**Issue by CyberSinh** [alphaleonis/AlphaFS#212]
Hi,

Congratulations for you great library I use in my sync software: Echosync.

`DirectoryEnumerationOptions.ContinueOnException` is a great option but it would be great also to have a way to retrieve errors happened during the enumeration.

What do you think about this idea?

Thanks again.

Regards,

Cyber Sinh

**Comment by Zuldan** [comment]
Great suggestion, I need this feature as well.

**Comment by besoft** [comment]
I have implemented this feature: you may pass a set of filters into overloaded Enumerate methods and with DirectoryEnumerationOptions.ContinueOnException OFF your callback filter will be called. In your callback method you may log the error, ask the user, etc. and if the process should continue (as with DirectoryEnumerationOptions.ContinueOnException ON) your method will return true, false otherwise.
