### ISSUE TITLE
How to build this on mono for linux?

### ISSUE THREAD

**Issue by ArsenShnurkov** [alphaleonis/AlphaFS#213]
Some project depend on this library, so I need to build it too.
Which standard describe "Long UNC" names?
Which parts of code should be excluded during linux build?

I know that "it is not supported on linux", "it is windows dependent", "there is no way to do that".

I need a way to build it (exact advices on codeblocks which should be removed or replaced)

**Comment by ArsenShnurkov** [comment]
https://msdn.microsoft.com/en-us/library/gg465305.aspx

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath

"To specify an extended-length path, use the "\\?\" prefix. For example, "\\?\D:\very long path""

"The maximum path of 32,767 characters is approximate, because the "\\?\" prefix may be expanded to a longer string by the system at run time, and this expansion applies to the total length."

"The "\\?\" prefix can also be used with paths constructed according to the **universal naming convention** (UNC). To specify such a path using UNC, use the "\\?\UNC\" prefix. For example, "\\?\UNC\server\share", where "server" is the name of the computer and "share" is the name of the shared folder."

---

For file I/O, the "\\?\" prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system. For example, if the file system supports large paths and file names, you can exceed the MAX_PATH limits that are otherwise enforced by the Windows APIs.

The "\\.\" prefix will access the Win32 device namespace instead of the Win32 file namespace. This is how access to physical disks and volumes is accomplished directly, without going through the file system, if the API supports this type of access. You can access many devices other than disks this way, for example 

```
type \\.\Volume{98fc8064-566a-11d9-82a2-806d6172696f}\out.txt
```

http://stackoverflow.com/questions/6867463/is-there-a-net-api-to-return-the-equivalent-extended-path-string-of-a-given-pat

**Comment by brutaldev** [comment]
Without having to create a Mono build of AplhaFS (which would be an enormous task), you could use processor directives in your own code to either use AplhaFS or the standard System.IO classes by compiling in the correct using statement.

```
#if MONO
using System.IO;
#else
using Alphaleonis.Win32.Filesystem;
#endif
```

Mono's implementation of System.IO supports long paths when running in Linux so the standard libs already work there.

You would obviously not be able to use any additional features that AphaFS provides and would need to stick the standard System.IO classes and method interfaces so that building normally or building for Mono is completely interchangeable.
