### ISSUE TITLE
Improve methods Directory/File.CopyMoveCore()

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#272]
Improve methods `Directory/File.CopyMoveCore()`

Possible to-do's:

**1. Improve detection of same volume;**
Applies to moving of files/folders. `Volume.IsSameVolume()` is used to check if the source and destination paths are on the same volume. This works well, even if source is a local path and destination a UNC path.
For example: Move from source : `C:\Temp\testfolder1` to destination : `\\host\C$\Temp\testfolder2`
However, the used Win32 API: `MoveFile()` fails miserably when encountering this combination of paths; it seems that the paths are only compared as strings by this function. A working solution is to apply some additional checks like doing our own path string comparison against local <> UNC paths.

**2. Eliminate recursion;**
`Directory.Move()` is recursive when it needs to copy an entire folder. Deep recursion eventually leads to stack overflow exceptions. Although I haven't yet encountered this with the current version of AlphaFS.
An alternative to recursion is the use of [trampoline](http://v2matveev.blogspot.nl/2010/03/fun-with-recursion.html). This means implementing a new folder copy mechanism.

**3. Make code recursive-aware, skip additional path checks and validations;**
In recursion mode, `Directory.Copy()` performs path checks and validations for all items returned from directory enumeration. By making use of `pathFormat != PathFormat.LongFullPath` these additional checks can be skipped, improving overall performance.

These enhancements are quite easy to implement and will not break anything.

**4. Combine (reduce) overloaded methods or, perhaps better, remove overloads.**
Including Transacted methods, there are currently 16 `Copy()` and 12 `Move()` methods.
Some of the methods return a `CopyMoveResult` class containing some info about the action. Other methods just return nothing (void). We could reduce the number by modifying the void methods to return a `CopyMoveResult` class, of course excluding the default .NET implementation.
The `CopyMoveResult` class can also be extended with some additional properties like `TotalFiles` and `TotalFolders`, since these numbers can be gathered during the copy progress. This is a breaking change since method signatures would be modified.

**5. Introduce a: `Clone()` method with a `CloneOptions` parameter class to specify copy/move actions.**
We could also opt for this new method with an options class to greatly reduce the number of overload methods.

**Comment by Yomodo** [comment]
@alphaleonis Any thoughts on this?

**Comment by alphaleonis** [comment]
It was a long time since I looked at this. But I would like a somewhat thorough explanation of each of the points in the list above; what each of the item achieves and how it can be done, and any changes to public interfaces that they would mean.

**Comment by Yomodo** [comment]
@alphaleonis Here you go! :)

**Comment by Yomodo** [comment]
I've filed a bug at Microsoft [Connect](https://connect.microsoft.com/VisualStudio/feedback/details/3105340/win32-api-function-movefilewithprogress).

**Comment by alphaleonis** [comment]
These sound like good suggestions with good explanations. (I took the liberty of adding numbers to the different items to make it easier to discuss them).

**1.** This sounds like a good idea, but how does comparing them ourselves help if we use the underlying Win32-function in the end, if that still will fail?

**2.** While you are right, recursion may lead to an SO-exception, I've yet to see one in real life that wasn't due to infinite recursion. The stack is pretty large in C# by default, but still, it may be a reasonable thing to fix.  The trampoline link you supplied was an interesting method, but is quite likely less efficient due to invocation via delegates and delegate creations.  Then again, these operations a mostly IO-bound, so that performance hit is probably negligible. A third option of course would be to simply use a `Stack<>` or similar collection and rewrite the recursion to be iterative instead.  

**3.** Sounds straightforward enough, and a good idea.

**4.** Not sure why we would like to, or need to, reduce the number of overloads here. After all, it seems they all just call the same method in the end (`CopyMoveCore`)?  So there isn't really a maintenance issue?  Changing a method signature from returning `void` to returning something else does not seem to be much of a breaking change as long as the rest of the method signature is the same.  But what is the main motivation for reducing the number of overloads here?

**5.** Unfortunately I don't quite understand what you mean here, could you elaborate a bit more?

Anyway, I think we should create separate issues for numer **1**, **2** and **3** above, since these are non-breaking and sounds like good ideas.  And I'll await your response regarding item 4 and 5. :)

**Comment by Yomodo** [comment]
**1.** I've managed to do it this way for method `CopyMoveCore`: 

![capture](https://cloud.githubusercontent.com/assets/10358198/19093734/a70a13be-8a8c-11e6-9e65-75c27374640a.PNG)

**2.** Perhaps instead of `Stack<>` we can even use the `Queue<>` which is already being used in the `FindFileSystemEntryInfo.Enumerate` method.

**4./5.** The new method, something like:
`public static void Clone(string sourcePath, string destinationPath, CloneOptions cloneOptions)`
The `Clone` method would combine the Copy/Move action and the `cloneOptions` class/structure would then accommodate all the parameters that are now used for the overloaded methods, which seems more efficient instead of having overloads where each overload has a new parameter.

Better yet: I think we should disregard this one because we would end up with: `Copy`, `Move` and a `Clone` which can do both. Besides, we need to keep the default `Copy` and `Move` methods from `System.IO`.

**Comment by alphaleonis** [comment]
Okay, sounds good. Let's disregard 4/5 then. And when it comes to 2 I don't know which is best, Queue or Stack, only determines the order in which things are made I guess. :)
