### ISSUE TITLE
Methods for adding alternate data streams should return a stream.

### ISSUE THREAD

**Issue by alphaleonis** [alphaleonis/AlphaFS#28]
Currently they accept only a string-array, which is unnecessarily restrictive. A better option would be to have the "AddStream" method return a Stream, and let the user write the data as he/she pleases. It is a "stream" after all.

**Comment by Yomodo** [comment]
Great!

**Comment by alphaleonis** [comment]
Fixed in #59... well, sort of.

**Comment by Yomodo** [comment]
:( The with the previous implementation, streams could also be added/removed to directories, are rare feature found on the net.

This is a nifty feature because for example you can now also get the real size used by dat folder, because of alternate data streams.

FindFirstStreamW does not work on directories, that why I didn't use that.

**Comment by alphaleonis** [comment]
Uhm, in my tests these work fine on directories as well. Also adding streams to directories works fine still.

For example:

```
// E:\Test is a directory
foreach (var stream in File.EnumerateAlternateDataStreams(@"\\?\E:\Test", PathFormat.LongFullPath))
{
   Console.WriteLine("Name: {0}", stream.StreamName);
}

using (FileStream fs = File.Open(@"\\?\E:\Test:myStream", System.IO.FileMode.Create, System.IO.FileAccess.Write, System.IO.FileShare.None, ExtendedFileAttributes.BackupSemantics, PathFormat.LongFullPath))
{
   fs.WriteByte(24);
}
```

If you want the other stream information, eg. non-data streams you can get those by using `BackupFileStream`. So no functionality has in that sense been removed.
