### ISSUE TITLE
Property FileSystemEntryInfo.AlternateFileName is always an empty string.

### ISSUE THREAD

**Issue by Yomodo** [alphaleonis/AlphaFS#286]
The methods `EnumerateFileSystemEntryInfosCore()` and `GetFileSystemEntryInfoCore()`  use, by default, the `DirectoryEnumerationOptions.BasicSearch` option.

Using this option improves retrieving file system objects by **not** [querying the short file name.](https://msdn.microsoft.com/nl-nl/library/windows/desktop/aa364415%28v=vs.85%29.aspx)

This means that the results from these methods with a return type of `FileSystemEntryInfo` will **always** have an empty string for the short name.

The fix is easy: Remove the `DirectoryEnumerationOptions.BasicSearch` option as default from these methods.

However, I think this should be a breaking change, since the enumeration performance can be effected. To prevent this possible impact on performance, one has to add the `DirectoryEnumerationOptions.BasicSearch` option to their code.

**Comment by alphaleonis** [comment]
It would be a breaking change if we went the other way. Not sure I'd see it as a breaking change in this case, since no-one likely relies on the fact the AlternateFileName is empty.  So I wouldn't say it's a breaking change since no-one will have to change their source-code to have it compile or to have the same behavior as before, even though the speed may be slightly affected of course.  But I'm guessing the reason is you think it should be done in _develop_ rather than _master_? Which sounds fine to me.

Aslo, the title should probably read `FileSystemEntryInfo.AlternateFileName` since this is what is publically exposed?

**Comment by Yomodo** [comment]
Yeah you're right, not a breaking change and, of course, for the develop branch.

**Comment by Yomodo** [comment]
Will leave it as-is for now. I really doubt if anyone will use the `AlternateFileName` property nowadays.

**Comment by Yomodo** [comment]
Commit 04976c4 fixes this.
