### ISSUE TITLE
Fix .gitignore to accommodate new directory structure in AlphaFS.UnitTest project

### ISSUE THREAD

**Issue by damiarnold** [alphaleonis/AlphaFS#371]
Since the 2.1.3 release, it appears that the files under `AlphaFS.UnitTest\Classes` folder have been relocated.  In particular, the `AlphaFS_BackupFileStream.cs` file (which appears to have been renamed to `AlphaFS_BackupFileStream_InitializeInstance_LocalAndNetwork_Success.cs`) in the **develop** branch is now missing, since the new folder which it was supposedly moved to is named `BackupStreamInfo Class`.
This is problematic, since in **.gitignore** there is this line:
`Backup*/`
which ignores all files under this new folder.  As a result, the currently development branch cannot be fully compiled without copying an older copy of the AlphaFS_BackupFileStream.cs file from a previous commit.

Not sure if you would prefer to change the .gitignore entry, or rename the `BackupStreamInfo Class` folder, but in any case manual work is needed to compile the development branch at this point.

**Comment by alphaleonis** [comment]
Ouch... nice catch.

I have removed `Backup*/` from .gitignore.  

@Yomodo Do you have that file locally? Not sure if it has changed since it was moved, but it is not located in source control.  If you have it and it builds and works for you, could you commit it to the repo as well (now that I have removed it from .gitignore)?

**Comment by Yomodo** [comment]
I've added the missing unit test file.

**Comment by damiarnold** [comment]
Thanks!   Looks like the solution is building without errors, now.
