### ISSUE TITLE
Directory.ExistsDriveOrFolderOrFile fails on global root path, so a simple file copy from a shadow copy fails with "device GLOBALROOT not ready"

### ISSUE THREAD

**Issue by CyberSinh** [alphaleonis/AlphaFS#433]
Seems to be a very severe bug!
Hope my simple #432 pull request could help.
Thank you for this wonderful library.

**Comment by Yomodo** [comment]
Thanks!

**Comment by Yomodo** [comment]
Fixed with #432

**Comment by CyberSinh** [comment]
Since this is a severe bug, would it be possible to release a new version 2.2.1 of AlphaFS (nuget package) soon?

**Comment by Yomodo** [comment]
I guess the severity is (only) related to shadow file copying, and not with regular file copies.
@alphaleonis Any thoughts on this?

**Comment by alphaleonis** [comment]
Yeah, the global root paths are not commonly used outside of Shadow copies to my knowledge, but then again, the reason for starting with AlphaFS in the first place was actually to support copying files from shadow copies, so it's a good point. If the bug is fixed I'll do a new release shortly. 

@Yomodo Was the fix only done on develop or also on master?

**Comment by Yomodo** [comment]
@alphaleonis Only in develop.

**Comment by alphaleonis** [comment]
@Yomodo Okay. Bugfixes should preferrably be made in master, so that new features can be worked on in develop while still releasing minor bugfix releases. But since that's the only fix made so far I'll just merge it down to master and create a new release from there. :)

**Comment by alphaleonis** [comment]
Fixed in 2.2.1 which has been released now. :)
